<?php
/** @var Mirasvit\DynamicCategory\Ui\Category\Form\Block\Rule $block */
?>

<div class="admin__fieldset" style="padding-top: 0;">
    <div class="admin__field">
        <div class="admin__field-label">
            <label><span><?= __('Products Selection Conditions') ?></span></label>
        </div>

        <div class="admin__field-control mst-rule-conditions">
            <div class="mst-admin__field-warning message message-warning" style="display: none" data-bind="scope: 'mstDynamicCategoryConditionWarning'">
                <span><?= __('"Parent Only" and "Child Only" conditions can slow down the indexing process.') ?></span>
            </div>

            <?= $block->getConditionsHtml() ?>

            <div class="admin__field-note">
                <span><?= __('Only products matched by rule will be present in the category after save.') ?></span>
            </div>
        </div>
    </div>

    <?php if ($block->isPreviewAllowed()): ?>
    <div class="admin__field">
        <div class="admin__field-label">&nbsp;</div>

        <div class="admin__field-control">
            <div data-bind="scope: 'mstDynamicCategoryProductsPreview'">
                <!-- ko template: getTemplate() --><!-- /ko -->
                <button id="dynamic-category-refresh" type="button" class="action-default scalable action-secondary" data-dynamic-category="refresh"
                        title="<?= __('Preview Products') ?>">
                    <span><?= __('Preview Products') ?></span>
                </button>
            </div>
        </div>
    </div>
    <?php endif; ?>
</div>


<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "mstDynamicCategoryProductsPreview": {
                        "component": "Mirasvit_DynamicCategory/js/preview",
                        "config": <?= $block->getPreviewJson(); ?>
                    },
                    "mstDynamicCategoryConditionWarning": {
                        "component": "Mirasvit_DynamicCategory/js/condition",
                        "config": <?= $block->getPreviewJson(); ?>
                    }
                }
            }
        }
    }








</script>
